### ISSUE TITLE
MIDI keyboard out of tune through the pi-stomp

### ISSUE THREAD

**Issue by MarnixMeersman** [TreeFallSound/pi-stomp#60]
Hi, 

I guess this either due to the soundcard or a setting in the MOD UI, but for some reason my midi keyboard is 40 cents out of tune when I use it through the pi-stomp. The problem seems to be with the pi stomp as the same keyboard plugged into a DAW like garageband is perfectly in tune. I also tried different generator plugins in the MOD plugin library, but all of them heb the same pitch shift. 

Regards, 
Marnix

**Comment by rreichenbach** [comment]
This is almost for sure a problem that we discovered recently with the initialization of the IQAudio Codec Zero audio card.  It causes problems for plugins which rely on sample rate including tuner, pitch shift and tone generators.  For example, playing the A string on a guitar thru the Tuna Tuner will show a frequency of around 117Hz instead of 110Hz as it should.

Micah applied a fix earlier this month to reinitialize the card upon every boot.  To get this change, you'll unfortunately need to reinstall from scratch:

https://www.treefallsound.com/wiki/doku.php?id=software_installation_64-bit

If you try this, please report back on whether this fixes the issue you are seeing.
