### ISSUE TITLE
Power Supply

### ISSUE THREAD

**Issue by MarnixMeersman** [TreeFallSound/pi-stomp#86]
Hi,

I think I fried my power supply for the pi stomp core. At least I hope it is the power supply as I saw a spark and now I cannot even get a white screen anymore. 

I remember that the the power supply had to be extremely low noise etc. Is there somewhere a list of specs on the power supply such that I can buy another one? I'm based in Europe, so re ordering one from the US is maybe a bit overkill. 

Thanks!

**Comment by micahvdm** [comment]
5v 2A, but if you can get a 3A, that would be better!

Can you try powering the unit with micro usb via the pi power in?

**Comment by rreichenbach** [comment]
If you have a multi-meter, it might be worth testing the supply voltage before scrapping it.  Frying the pi would have a similar behavior.  It's also possible that the polyfuse on the pi-Stomp (near the power jack) was tripped.  It should re-heal after it cools, but that's worth checking too.  It should appear as a short when working correctly.

The most important specs for a supply, as Micah points out are the voltage and current.  2Amp is plenty for a pi3A+

But you should also know that the DC barrel jack is unique.  It's a 2.5x5.5mm Center Positive.  That may look the same as the 9v (center negative) plug used on most guitar pedals, but was specifically chosen so that you cannot insert the plug from such a supply.

The one you had is a Cincon TRG1505.  
https://www.mouser.com/datasheet/2/75/Datasheet_TRG15_series-2997931.pdf

The specs that result in lower noise than most are the "Load Regulation" and the "Ripple Noise".  I would not recommend a supply with ripple greater than 70 or 80mV or load regulation much higher than 5%.  If a supply does not report its specs, you can guess it might be noisy.

Another good option is an official Raspberry Pi supply.  They have great noise specs.  They won't have the right barrel connector, but you can purchase an adapter:
https://www.amazon.com/gp/product/B07YFTZ4Z2/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

**Comment by MarnixMeersman** [comment]
I tested functionality with a raspi power supply and thank god everything functions properly. Thanks to both of you for the advice on getting a new power supply. I wll be ordering a new one soon.

**Comment by rreichenbach** [comment]
Ah, nice to hear that.  Thanks for reporting back.
